service:
  name: interview-test

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: local
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${opt:nodeEnv, self:provider.stage}
    # Add environment variables here such as mysql connection information, elasticsearch connection information, etc.

functions:
  employeeDelete:
    handler: handler.employeeDelete
    name: employeeDelete
    events:
      - http:
          path: employee/{id}
          method: delete

  employeePatch:
    handler: handler.employeePatch
    name: employeePatch
    events:
      - http:
          path: employee/{id}
          method: patch

  employeePost:
    handler: handler.employeePost
    name: employeePost
    events:
      - http:
          path: employee
          method: post

  employeeGet:
    handler: handler.employeeGet
    name: employeeGet
    events:
      - http:
          path: employee
          method: get
