#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [[ -h "$SOURCE" ]]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ ${SOURCE} != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

set -e;

if [[ -n "$1" ]]; then
  PROFILE=$1
fi;

if [[ -z "$AWS_PROFILE" ]]; then
  PROFILE=dev
fi;

node --inspect=127.0.0.1:9229 node_modules/.bin/serverless offline start \
-t -c --webpack-no-watch \
--stage ${PROFILE} \
--skipCacheInvalidation \
--port 9999;
